# WordPress recipe
name: SITE-NAME

# Start with the default WordPress recipe
recipe: wordpress

# Add in a proxy route to phpmyadmin
#proxy:
#  pma:
#    - pma.lemp.lndo.site

# Add in phpmyadmin
services:

  # Override the appsever to add some environment variables and install an extra VIM package
  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get upgrade -y"
      - "docker-php-ext-install pcntl"
#    overrides:
#      services:
#        environment:
#          MYCONFIGVAR1: secretpasscode

#  pma:
#
#    type: phpmyadmin
#
#    hosts:
#      - database

  cli:
    type: node:6.10


# Configure the WordPress recipe
config:

  php: '7.0'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true
  conf:

    server: wordpress2.conf
    php: config/php.ini

# Add a lando vim command
tooling:
  vim:
    service: appserver
  npm:
    service: cli
